In [8]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('./src/route_data/gps/asc2022/stage1_ckpt1.csv')
# df.latitude.values
df

type   latitude  longitude  altitude (ft)  course  slope (%)  \
0       T  39.092185 -94.417077         1045.4     NaN        NaN   
1       T  39.092184 -94.417187         1045.0     NaN       -2.6   
2       T  39.092197 -94.417811         1041.0     NaN       -2.6   
3       T  39.092212 -94.418348         1036.0     NaN       -2.6   
4       T  39.092216 -94.418486         1034.8     NaN       -2.6   
...   ...        ...        ...            ...     ...        ...   
2617    T  39.037653 -95.673454          893.1   287.3        0.7   
2618    T  39.037895 -95.674316          892.2   288.4        1.0   
2619    T  39.038100 -95.675036          899.2   289.1        0.9   
2620    T  39.038138 -95.675183          900.5   289.7        0.9   
2621    T  39.038337 -95.675887          899.9   289.9        1.6   

      distance (mi)  distance_interval (ft)    color  opacity  width  scale  \
0             0.000                     NaN  #0288d1      1.0    1.2    NaN   
1             0.006                   31.22      NaN      NaN    NaN    NaN   
2             0.039                  177.18      NaN      NaN    NaN    NaN   
3             0.068                  152.52      NaN      NaN    NaN    NaN   
4             0.076                   39.20      NaN      NaN    NaN    NaN   
...             ...                     ...      ...      ...    ...    ...   
2617        102.145                   22.25      NaN      NaN    NaN    NaN   
2618        102.195                  260.24      NaN      NaN    NaN    NaN   
2619        102.236                  217.72      NaN      NaN    NaN    NaN   
2620        102.244                   43.99      NaN      NaN    NaN    NaN   
2621        102.285                  212.70      NaN      NaN    NaN    NaN   

      sym                       name  desc  
0     NaN  A. Independence to Topeka   NaN  
1     NaN                        NaN   NaN  
2     NaN                        NaN   NaN  
3     NaN                        NaN   NaN  
4     NaN                        NaN   NaN  
...   ...                        ...   ...  
2617  NaN                        NaN   NaN  
2618  NaN                        NaN   NaN  
2619  NaN                        NaN   NaN  
2620  NaN                        NaN   NaN  
2621  NaN                        NaN   NaN  

[2622 rows x 15 columns]

In [20]:
df['course'].fillna(method='bfill')

0       271.7
1       271.7
2       271.7
3       271.7
4       271.7
        ...  
2617    287.3
2618    288.4
2619    289.1
2620    289.7
2621    289.9
Name: course, Length: 2622, dtype: float64

In [7]:
from datetime import datetime, date
datetime(2022, 8, 3).timestamp()

1659510000.0

In [1]:
from src.route import Route
from datetime import datetime
from src.util import print_dict

route = Route()

route.add_base_leg(
    './src/route_data/gps/asc2022/stage1_ckpt1.csv', 
    open=datetime(2022, 8, 2, 11, 15),
    release=datetime(2022, 8, 2, 11, 15),
    close=datetime(2022, 8, 2, 11, 15),
)

route.save_as("test")
new_route = Route.open('test')


print_dict(new_route.leg_list[0])

name:
	'A. Independence to Topeka'
open:
	datetime.datetime(2022, 8, 2, 11, 15)
release:
	datetime.datetime(2022, 8, 2, 11, 15)
close:
	datetime.datetime(2022, 8, 2, 11, 15)
dists:
	array([0.000e+00, 1.000e+02, 2.000e+02, ..., 1.645e+05, 1.646e+05,
       1.647e+05])
longitudes:
	array([-94.417077  , -94.41823944, -94.41937914, ..., -95.67468153,
       -95.67576599, -95.67683293])
latitudes:
	array([39.092185  , 39.09220897, 39.09223815, ..., 39.03799908,
       39.03830279, 39.03860439])
slopes:
	array([-2.6       , -2.6       , -2.79500823, ...,  0.94923127,
        1.47967602,  2.5405563 ])
headings:
	array([-94.417077  , -94.41823944, -94.41937914, ..., -95.67468153,
       -95.67576599, -95.67683293])


In [4]:
languages = ['Java', 'Python', 'JavaScript']
versions = [14, 3, 6]

result = zip(languages, versions)
print(list(result))

# Output: [('Java', 14), ('Python', 3), ('JavaScript', 6)]

[('Java', 14), ('Python', 3), ('JavaScript', 6)]


In [1]:
import src.visualcrossing as vc
from datetime import datetime

vc.get_weather_range(35, -97, datetime(2022, 8, 2), save='35,-97(2022,8,2).csv')

datetimeEpoch  solarradiation  cloudcover  windspeed  winddir  precip  \
0      1659441600            23.0         0.0        8.7     31.0     0.0   
1      1659445200            47.0         0.0       11.6    175.0     0.0   
2      1659448800           322.0         0.0       16.9    186.0     0.0   
3      1659452400            77.0         0.0       20.9    213.0     0.0   
4      1659456000            79.0         0.0       23.2    214.0     0.0   
5      1659459600            76.0         0.0       21.1    217.0     0.0   
6      1659463200            83.0        17.9       18.3    217.0     0.0   
7      1659466800           912.0        55.3       21.7    197.0     0.0   
8      1659470400           821.0        50.0       17.8    191.0     0.0   
9      1659474000           747.0        41.6       16.9    187.0     0.0   
10     1659477600           561.0        31.8       20.0    195.0     0.0   
11     1659481200            88.0        41.6       18.7    185.0     0.0   
12     1659484800            47.0        15.1       18.8    187.0     0.0   
13     1659488400            21.0         0.0       15.0    170.0     0.0   

    temp                date  
0   24.2 2022-08-02 07:00:00  
1   25.9 2022-08-02 08:00:00  
2   28.6 2022-08-02 09:00:00  
3   31.7 2022-08-02 10:00:00  
4   34.1 2022-08-02 11:00:00  
5   35.4 2022-08-02 12:00:00  
6   36.4 2022-08-02 13:00:00  
7   37.2 2022-08-02 14:00:00  
8   37.8 2022-08-02 15:00:00  
9   38.4 2022-08-02 16:00:00  
10  37.8 2022-08-02 17:00:00  
11  37.6 2022-08-02 18:00:00  
12  36.5 2022-08-02 19:00:00  
13  34.9 2022-08-02 20:00:00

In [3]:
import src.visualcrossing as vc
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('35,-97(2022,8,2).csv', index_col='dates', parse_dates=True)
plt.plot(df.solar)

FileNotFoundError: [Errno 2] No such file or directory: '35,-97(2022,8,2).csv'

In [2]:
from src.util import *

latlong_dist((39, -95), (39, -95.01))

0.8641468813292867

In [7]:
a_dict = {'color': 'blue', 'fruit': 'apple', 'pet': 'dog'}
for key in a_dict:
    print(key)

thing = []

for key in a_dict:
    thing.append(key)

thing

color
fruit
pet


['color', 'fruit', 'pet']